In [1]:
import numpy as np
import pandas as pd
import torch 
from torch import nn
from torch.utils import data

import os

In [2]:
os.getcwd()

'D:\\Jupyter\\GDP_prediction'

In [3]:
train_data = pd.read_csv('T.csv')
train_data.head()

,DATE,GDP_China,Inflation_rate,Exchang_rate,Instsred_rate,Population,YounthUnempRate,Gold_price
0,2022-1-1,1.800000e+13,1.973576,6.729012,2.9,1412175000,13.165,12096.9
1,2021-1-1,1.780000e+13,0.981015,6.450814,2.9,1412360000,12.437,11602.0
2,2020-1-1,1.470000e+13,2.419422,6.904190,2.9,1411100000,12.688,12199.8
3,2019-1-1,1.430000e+13,2.899234,6.908139,2.9,1407745000,10.730,9634.9
4,2018-1-1,1.390000e+13,2.074790,6.609043,2.9,1402760000,9.714,8384.1

In [4]:
train_data.tail()

,DATE,GDP_China,Inflation_rate,Exchang_rate,Instsred_rate,Population,YounthUnempRate,Gold_price
37,1985-1-1,3.090000e+11,NaN,2.943430,NaN,1051040000,NaN,926.6
38,1984-1-1,2.600000e+11,NaN,2.330313,NaN,1036825000,NaN,NaN
39,1983-1-1,2.310000e+11,NaN,1.981013,NaN,1023310000,NaN,NaN
40,1982-1-1,2.050000e+11,NaN,1.897860,NaN,1008630000,NaN,NaN
41,1981-1-1,1.960000e+11,NaN,1.709976,NaN,993885000,NaN,NaN

In [5]:
print(train_data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   DATE             42 non-null     object
 1   GDP_China        42 non-null     float64
 2   Inflation_rate   36 non-null     float64
 3   Exchang_rate     42 non-null     float64
 4   Instsred_rate    32 non-null     float64
 5   Population       42 non-null     int64
 6   YounthUnempRate  32 non-null     float64
 7   Gold_price       38 non-null     float64
dtypes: float64(6), int64(1), object(1)
memory usage: 2.8+ KB
None

In [6]:
train_data.dropna(how='all')

,DATE,GDP_China,Inflation_rate,Exchang_rate,Instsred_rate,Population,YounthUnempRate,Gold_price
0,2022-1-1,1.800000e+13,1.973576,6.729012,2.900000,1412175000,13.165,12096.9
1,2021-1-1,1.780000e+13,0.981015,6.450814,2.900000,1412360000,12.437,11602.0
2,2020-1-1,1.470000e+13,2.419422,6.904190,2.900000,1411100000,12.688,12199.8
3,2019-1-1,1.430000e+13,2.899234,6.908139,2.900000,1407745000,10.730,9634.9
4,2018-1-1,1.390000e+13,2.074790,6.609043,2.900000,1402760000,9.714,8384.1
5,2017-1-1,1.230000e+13,1.593136,6.756870,2.900000,1396215000,10.474,8487.2
6,2016-1-1,1.120000e+13,2.000002,6.640016,2.900000,1387790000,10.612,8305.8
7,2015-1-1,1.110000e+13,1.437024,6.282743,3.191667,1379860000,10.714,7285.1
8,2014-1-1,1.050000e+13,1.921642,6.161989,3.250000,1371860000,10.535,7802.0
9,2013-1-1,9.570000e+12,2.621050,6.147754,3.250000,1363240000,10.338,8684.3
10,2012-1-1,8.530000e+12,2.619524,6.309263,3.250000,1354190000,10.168,10530.5
11,2011-1-1,7.550000e+12,5.553899,6.463020,3.250000,1345035000,9.982,10147.6
12,2010-1-1,6.090000e+12,3.175325,6.769602,2.828333,1337705000,9.820,8283.0
13,2009-1-1,5.100000e+12,-0.728165,6.830739,2.790000,1331260000,10.144,6642.6
14,2008-1-1,4.590000e+12,5.925251,6.947740,3.937500,1324655000,9.795,6064.4
15,2007-1-1,3.550000e+12,4.816768,7.605780,3.330000,1317885000,9.215,5284.8
16,2006-1-1,2.750000e+12,1.649431,7.972344,3.330000,1311020000,9.319,4813.3
17,2005-1-1,2.290000e+12,1.776414,8.193588,3.330000,1303720000,9.481,3639.5
18,2004-1-1,1.960000e+12,3.824637,8.276793,2.857500,1296075000,9.417,3386.6
19,2003-1-1,1.660000e+12,1.127603,8.277171,2.700000,1288400000,9.609,3007.2
20,2002-1-1,1.470000e+12,-0.731971,8.277051,2.745000,1280400000,8.907,2563.2
21,2001-1-1,1.340000e+12,0.719126,8.277013,3.240000,1271850000,7.986,2243.4
22,2000-1-1,1.210000e+12,0.347811,8.278412,3.240000,1262645000,6.835,2310.5
23,1999-1-1,1.090000e+12,-1.401473,8.278285,3.802500,1252735000,6.764,2306.1
24,1998-1-1,1.030000e+12,-0.773186,8.300752,6.112500,1241935000,6.668,2434.7
25,1997-1-1,9.620000e+11,2.786465,8.319331,8.887500,1230075000,6.567,2746.4
26,1996-1-1,8.640000e+11,8.313160,8.338875,9.480000,1217550000,6.262,3224.9
27,1995-1-1,7.340000e+11,16.791225,8.370025,10.350000,1204855000,5.924,3206.9
28,1994-1-1,5.640000e+11,24.256990,8.639665,10.080000,1191835000,5.626,3306.3
29,1993-1-1,4.450000e+11,14.610079,5.779529,8.850000,1178440000,5.121,2077.2
30,1992-1-1,4.270000e+11,6.353981,5.520570,7.200000,1164970000,4.434,1902.4
31,1991-1-1,3.830000e+11,3.556686,5.333729,7.380000,1150780000,4.366,1927.4
32,1990-1-1,3.610000e+11,3.052290,4.792069,NaN,1135185000,NaN,1827.1
33,1989-1-1,3.480000e+11,18.245638,3.767348,NaN,1118650000,NaN,1434.3
34,1988-1-1,3.120000e+11,18.811818,3.731400,NaN,1101630000,NaN,1626.1
35,1987-1-1,2.730000e+11,7.233836,3.731400,NaN,1084035000,NaN,1659.6
36,1986-1-1,3.010000e+11,NaN,3.461615,NaN,1066790000,NaN,1272.4
37,1985-1-1,3.090000e+11,NaN,2.943430,NaN,1051040000,NaN,926.6
38,1984-1-1,2.600000e+11,NaN,2.330313,NaN,1036825000,NaN,NaN
39,1983-1-1,2.310000e+11,NaN,1.981013,NaN,1023310000,NaN,NaN
40,1982-1-1,2.050000e+11,NaN,1.897860,NaN,1008630000,NaN,NaN
41,1981-1-1,1.960000e+11,NaN,1.709976,NaN,993885000,NaN,NaN

In [7]:
#Because the data is a time series, the nearest value is used instead of the np.nan value
fill_list = ['Inflation_rate','Instsred_rate','YounthUnempRate','Gold_price']

for name in fill_list:
    temp = None
    index = train_data.shape[0]
    for ele in reversed(train_data[name]):
        #print(ele)
        index -= 1
        if pd.notnull(ele) == True:
            temp = ele
            break
    #print(index , temp)
    train_data[name] = train_data[name].fillna(temp)
    
train_data

,DATE,GDP_China,Inflation_rate,Exchang_rate,Instsred_rate,Population,YounthUnempRate,Gold_price
0,2022-1-1,1.800000e+13,1.973576,6.729012,2.900000,1412175000,13.165,12096.9
1,2021-1-1,1.780000e+13,0.981015,6.450814,2.900000,1412360000,12.437,11602.0
2,2020-1-1,1.470000e+13,2.419422,6.904190,2.900000,1411100000,12.688,12199.8
3,2019-1-1,1.430000e+13,2.899234,6.908139,2.900000,1407745000,10.730,9634.9
4,2018-1-1,1.390000e+13,2.074790,6.609043,2.900000,1402760000,9.714,8384.1
5,2017-1-1,1.230000e+13,1.593136,6.756870,2.900000,1396215000,10.474,8487.2
6,2016-1-1,1.120000e+13,2.000002,6.640016,2.900000,1387790000,10.612,8305.8
7,2015-1-1,1.110000e+13,1.437024,6.282743,3.191667,1379860000,10.714,7285.1
8,2014-1-1,1.050000e+13,1.921642,6.161989,3.250000,1371860000,10.535,7802.0
9,2013-1-1,9.570000e+12,2.621050,6.147754,3.250000,1363240000,10.338,8684.3
10,2012-1-1,8.530000e+12,2.619524,6.309263,3.250000,1354190000,10.168,10530.5
11,2011-1-1,7.550000e+12,5.553899,6.463020,3.250000,1345035000,9.982,10147.6
12,2010-1-1,6.090000e+12,3.175325,6.769602,2.828333,1337705000,9.820,8283.0
13,2009-1-1,5.100000e+12,-0.728165,6.830739,2.790000,1331260000,10.144,6642.6
14,2008-1-1,4.590000e+12,5.925251,6.947740,3.937500,1324655000,9.795,6064.4
15,2007-1-1,3.550000e+12,4.816768,7.605780,3.330000,1317885000,9.215,5284.8
16,2006-1-1,2.750000e+12,1.649431,7.972344,3.330000,1311020000,9.319,4813.3
17,2005-1-1,2.290000e+12,1.776414,8.193588,3.330000,1303720000,9.481,3639.5
18,2004-1-1,1.960000e+12,3.824637,8.276793,2.857500,1296075000,9.417,3386.6
19,2003-1-1,1.660000e+12,1.127603,8.277171,2.700000,1288400000,9.609,3007.2
20,2002-1-1,1.470000e+12,-0.731971,8.277051,2.745000,1280400000,8.907,2563.2
21,2001-1-1,1.340000e+12,0.719126,8.277013,3.240000,1271850000,7.986,2243.4
22,2000-1-1,1.210000e+12,0.347811,8.278412,3.240000,1262645000,6.835,2310.5
23,1999-1-1,1.090000e+12,-1.401473,8.278285,3.802500,1252735000,6.764,2306.1
24,1998-1-1,1.030000e+12,-0.773186,8.300752,6.112500,1241935000,6.668,2434.7
25,1997-1-1,9.620000e+11,2.786465,8.319331,8.887500,1230075000,6.567,2746.4
26,1996-1-1,8.640000e+11,8.313160,8.338875,9.480000,1217550000,6.262,3224.9
27,1995-1-1,7.340000e+11,16.791225,8.370025,10.350000,1204855000,5.924,3206.9
28,1994-1-1,5.640000e+11,24.256990,8.639665,10.080000,1191835000,5.626,3306.3
29,1993-1-1,4.450000e+11,14.610079,5.779529,8.850000,1178440000,5.121,2077.2
30,1992-1-1,4.270000e+11,6.353981,5.520570,7.200000,1164970000,4.434,1902.4
31,1991-1-1,3.830000e+11,3.556686,5.333729,7.380000,1150780000,4.366,1927.4
32,1990-1-1,3.610000e+11,3.052290,4.792069,7.380000,1135185000,4.366,1827.1
33,1989-1-1,3.480000e+11,18.245638,3.767348,7.380000,1118650000,4.366,1434.3
34,1988-1-1,3.120000e+11,18.811818,3.731400,7.380000,1101630000,4.366,1626.1
35,1987-1-1,2.730000e+11,7.233836,3.731400,7.380000,1084035000,4.366,1659.6
36,1986-1-1,3.010000e+11,7.233836,3.461615,7.380000,1066790000,4.366,1272.4
37,1985-1-1,3.090000e+11,7.233836,2.943430,7.380000,1051040000,4.366,926.6
38,1984-1-1,2.600000e+11,7.233836,2.330313,7.380000,1036825000,4.366,926.6
39,1983-1-1,2.310000e+11,7.233836,1.981013,7.380000,1023310000,4.366,926.6
40,1982-1-1,2.050000e+11,7.233836,1.897860,7.380000,1008630000,4.366,926.6
41,1981-1-1,1.960000e+11,7.233836,1.709976,7.380000,993885000,4.366,926.6

In [8]:
#delete listTime and separate label&feature  (function : iloc 和 slice 操作)
all_feature = train_data.iloc[:,2:]
all_label = train_data['GDP_China']

In [9]:


numeic_feature = all_feature.dtypes[all_feature.dtypes != 'object'].index

numeic_feature

Index(['Inflation_rate', 'Exchang_rate', 'Instsred_rate', 'Population',
       'YounthUnempRate', 'Gold_price'],
      dtype='object')

In [10]:
#DATA standardization(Z-zero)
all_feature[numeic_feature] = all_feature[numeic_feature].apply(
                    lambda x : (x - x.mean()) / x.std() 
)

In [11]:
#creat Tensor
train_feature = torch.tensor(all_feature.values,dtype=torch.float32)
train_label = torch.tensor(all_label.values,dtype=torch.float32)

#  float32 !!!很重要,DL常用32

In [12]:
#craet Tensordataset + compute iteration
def load_array(dataarray,batach_size,is_train=True): #dataarray include feature & labels
    dataset = data.TensorDataset(*dataarray) # paramter : Tuple[Tensor,...]
    return data.DataLoader(dataset,batach_size,shuffle=is_train)

In [13]:
Loss = nn.MSELoss()
#Single layer linear perceptron
def get_net():
    net = nn.Sequential(nn.Linear(train_feature.shape[1],1))
    return net

def log_rmse(net,feature,label):
    clipps_preds = torch.clamp(net(feature),1,float('inf'))
    rmse = torch.sqrt(Loss(torch.log(clipps_preds),torch.log(label)))
    return rmse

In [14]:
def train(net,train_feature,train_label,test_feature,test_label,num_epoch,learning_rate,weight_decay,batach_size):
    #test_feature,test_label 是为了方便交叉验证
    train_loss,test_loss=[],[]
    train_iteration = load_array((train_feature,train_label),batch_size)
    optimizer = torch.optim.Adam(net.parameters(),lr=learning_rate,weight_decay=weight_decay)
    for epoch in range(num_epoch):
        for X,y in train_iteration:
            optimizer.zero_grad()
            l=Loss(net(X),y)
            l.backward()
            optimizer.step()
        train_loss.append(log_rmse(net,train_feature,train_label))
        if test_label is not None:
            test_loss.append(log_rmse(net, test_feature, test_label))
    return train_loss,test_loss

In [15]:
def sliceTrainValid_k_fold(k,i,X,y):
    assert k >1
    X_train,y_train = None,None
    fold_size = X.shape[0] // k
    for j in range(k):
        sli=slice(j * fold_size,(j+1) * fold_size)
        X_part = X[sli,:]
        y_part = y[sli]
        if j==i:
            X_valid = X_part
            y_vaild = y_part
        elif X_train is None:
            X_train = X_part
            y_train = y_part
        else:
            X_train = torch.cat([X_train,X_part],0)
            y_train = torch.cat([y_train,y_part],0)
    return X_train,y_train,X_valid,y_vaild

In [16]:
def k_times_k_fold_CrossValidation(k,X_train,y_train,num_epoch,learning_rate,weight_decay,batch_size):
    train_loss_sum , valid_loss_sum = 0,0
    for i in range(k):
        data = sliceTrainValid_k_fold(k,i,X_train,y_train)
        net = get_net()
        train_loss,valid_loss = train(net, *data,num_epoch,learning_rate,weight_decay,batch_size)
        train_loss_sum += train_loss[-1]
        valid_loss_sum += valid_loss[-1]
        print(f'fold-{i+1} trainset log_rmse{float(train_loss[-1]):f}  '+ f'fold-{i+1} validset log_rmse{float(valid_loss[-1]):f}')
    return train_loss_sum/k , valid_loss_sum/k

In [17]:
#Debug hyperparameter

k , num_epoch,learning_rate,weight_decay,batch_size=6,100,5,0,1

train_averg_loss,valid_averg_loss =k_times_k_fold_CrossValidation(k ,train_feature,train_label,num_epoch,learning_rate,weight_decay,batch_size)
print(f'train_averg_loss{float(train_averg_loss):f},  ' +f'valid_averg_loss{float(valid_averg_loss):f}')

D:\Anaconda3\envs\DL\lib\site-packages\torch\nn\modules\loss.py:530: UserWarning: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
D:\Anaconda3\envs\DL\lib\site-packages\torch\nn\modules\loss.py:530: UserWarning: Using a target size (torch.Size([35])) that is different to the input size (torch.Size([35, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
D:\Anaconda3\envs\DL\lib\site-packages\torch\nn\modules\loss.py:530: UserWarning: Using a target size (torch.Size([7])) that is different to the input size (torch.Size([7, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)

fold-1 trainset log_rmse22.792404  fold-1 validset log_rmse19.437176
fold-2 trainset log_rmse22.875189  fold-2 validset log_rmse19.099939
fold-3 trainset log_rmse23.282368  fold-3 validset log_rmse17.973122
fold-4 trainset log_rmse22.479891  fold-4 validset log_rmse22.393320
fold-5 trainset log_rmse21.142628  fold-5 validset log_rmse26.712736
fold-6 trainset log_rmse21.213472  fold-6 validset log_rmse26.245813
train_averg_loss22.297659,  valid_averg_loss21.977018

In [18]:
#read test_data

#test_data=pd.read('test.csv')

#test_feature = torch.tensor(test_data.values,dtype=float32)

In [19]:
def trainInAll_and_pred(train_feature, test_feature, train_label,test_data,num_epochs, lr, weight_decay, batch_size):
    net = get_net()
    train_loss,_ = train(train_feature,train_label,None,None,num_epochs, lr, weight_decay, batch_size)
    print(f'train_lossMse {float(train_loss[-1]):f}  ')
    predicted = net(test_feature).detach().numpy()
    test_data['ChinaGDP_predicted']=pd.Series(predicted.reshape(1,-1)[0])
    test_data.to_csv('result.csv',index=False)

In [ ]:
trainInAll_and_pred(train_feature, test_feature, train_label,test_data,
                        num_epoch, lr, weight_decay, batch_size)